### PR TITLE
fix: status should change

### LINKED ISSUE #9: status never change
https://github.com/pmndrs/jotai/pull/1435#issuecomment-1282394281 by @EduardoLopes

> I've found another bug. The `fetchStatus`, `isInitialLoading` and others status never change. 
> 
> I did a reproduction comparing to tanstack/query return: https://codesandbox.io/s/winter-water-kdysdj?file=/src/App.tsx

### PR DESCRIPTION
**Pull request by dai-shi**
close #9

### CODE REVIEW

**Comment by EduardoLopes** [comment]
nice! it works here :sparkles:

File: src/common.ts [hunk 1]
```diff
@@ -59,8 +59,12 @@ export const createAtoms = <
     const observable = {
       subscribe: (arg: { next: (result: Result) => void }) => {
         const callback = (result: Result) => {
-          if (!(observer as any)[SKIP_LISTENERS]) {
-            ;(typeof arg === 'function' ? arg : arg.next)(result)
+          const notifyResult = () =>
+            (typeof arg === 'function' ? arg : arg.next)(result)
+          if ((observer as any)[IN_RENDER]) {
+            Promise.resolve().then(notifyResult)
```
Comment (mwisnicki) [inline src/common.ts:65]: Just curious how this works. Isn't this just the same as `notifyResult()`?

File: __tests__/issue_9_spec.tsx [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+import { atomsWithTanstackQuery } from '../src/index'
+
+describe('issue #9', () => {
+  it('status should change', async () => {
+    const idAtom = atom(undefined as number | undefined)
+
+    const [, statusAtom] = atomsWithTanstackQuery((get) => ({
+      queryKey: ['users', get(idAtom)],
+      queryFn: async ({ queryKey: [, id] }) => {
+        await new Promise((resolve) => setTimeout(resolve, 100))
```
Comment (mwisnicki) [inline __tests__/issue_9_spec.tsx:13]: IMHO better to resolve this explicitly rather than relying on timing. This test might be flaky on busy machine (e.g. if process suddenly get preempted for >100ms between lines 56 & 57.

Comment (dai-shi) [reply __tests__/issue_9_spec.tsx:13]: Yeah, I always felt that. Good point. I can try.

File: src/common.ts (hunk 1 above)
Comment (dai-shi) [reply src/common.ts:65]: It delays for one tick or so. This is a hack to avoid React warning. I wish there's a better solution.

File: __tests__/issue_9_spec.tsx (hunk 2 above)
Comment (dai-shi) [reply __tests__/issue_9_spec.tsx]: f8cbdaa
Do you have a better idea?
We did so many setTimeout hack in https://github.com/pmndrs/jotai tests, and I wanted someone for help.

File: src/common.ts (hunk 1 above)
Comment (mwisnicki) [reply src/common.ts:65]: Interesting. I usually use `setTimeout(...,0)` in such cases and I thought resolved promise will continue immediately avoiding queuing but looks like it doesn't although it does have a higher priority than `setTimeout`.

```
(() => {
  setTimeout(()=>console.log(1), 0);
  Promise.resolve().then(() => console.log(2));
  console.log(3);
})()
```
```
3
2
1
```

File: __tests__/issue_9_spec.tsx (hunk 2 above)
Comment (mwisnicki) [reply __tests__/issue_9_spec.tsx]: > [f8cbdaa](https://github.com/jotai-labs/jotai-tanstack-query/commit/f8cbdaa3d98f10fe8830d9f909bf8ee5f9ade6f1) Do you have a better idea?

This is probably as good as it gets. I didn't find any popular testing lib with promise mocks.
If this is used many times then probably some kind of helper could be handy.

```ts
function mockPromise<T = void>() {
    let resolve: (value: T) => void;
    let promise = new Promise<T>((r) => resolve = r);
    return Object.assign(promise, {resolve: resolve!});
}

const p = mockPromise();
p.then(() => console.log("hello"));
p.resolve();
```
